global:
  scrape_interval: 10s
  external_labels:
    monitor: 'demo'

scrape_configs:
  - job_name: 'trustingsocial_ocmetrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
